BB BBBBBBBB
    XXX XXXXXXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            XXX BB BBBBBBBBBBBB XXXXXXXXXXXX  XXXXX XXXXXXXBBBBB X

                
            XXXXX
        BBBBBB
    XXXXX
BBBBB