
BBBB BBBBBB
BBBB BBBB

XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Dashboard') 
              XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBBBXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Expenses') 
              XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Income') 
              XXXX

          XXXXX

          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Summary') XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX X XXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                gettext(u'Expenses Summary') 
              XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Income Summary') 
              XXXX
            XXXXX

          XXXXX

          XXX XXXXXXXXXXXXX

          XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Settings') 
              XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBXX
               BBBBBBBBBB XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Sign out') XX
              XXXXXXX
            XXXXX
          XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX X XXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBBBBBBXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              gettext(u'General') 
              XXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Account') 
              XXXX
            XXXXX

          XXXXX


        XXXXXX
      XXXXXX
    XXXXXX
