BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Preferred Currency') 
    	XXXXX
    XXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBB
  	
      XXXXXXX XXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXX
  BBBBB
      BBB BBBBBBBB BB BBBBBBBBBB

    XXXXXXX XXXX X XXXXXXXXXX XXXXXXXXX X XXXXXXXXX
      BBBBBB
  XXXXXXXXX
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
    XXXXXXX
    XXXXXX

BBBBBBBB BBBBBBB