BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX  XXXX XX

        XXXX XXXXXXXXXXXXXXXXXXXXXX XX
            XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX gettext(u'Income') XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add Income') XXXXX
            XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Amount') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Description') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Sources') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            BBB BBBBBB BB BBBBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Date of Income') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX


BBBBBBBB BBBBBBB

