BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX  XXXX XX

  XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XX
            XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Income') XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Edit Income') XXXXX
            XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Delete') XXXX
      XXXXXX
  XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Amount') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Description') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Sources') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                            BBB BBBBBB BB BBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Date of Income') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX X
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Save') XXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

    XXXXXXX XXXXXXXXXXXXXX
BBBBBBBB BBBBBBB

