BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX  XXXX XX

        XXXX XXXXXXXXXXXXXXXXXXXXXX XX
            XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Expenses') XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Add Expenses') XXXXX
            XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Amount') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Description') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Category') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Date of Expense') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Save') XXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX


BBBBBBBB BBBBBBB

