BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXX  XXXX XX

  XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XX
            XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXX gettext(u'Expenses') XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Edit Expenses') XXXXX
            XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
  XXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Amount') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Description') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Category') XXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                            BBB BBBBBBBB BB BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                            BBBBBB
                        XXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXX gettext(u'Date of Expense') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX X
                    XXXXXX

                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX

    XXXXXX

BBBBBBBB BBBBBBB

