BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
        XXXXX  X
            XXXXX XXX
            XXXXXXX XXXXX XXXXX XXXXX XXXXXX

        XXXXXXXXXXX X

            XXXXXXXX XXXXXX XXXXXXX
        X
     XXXXXXXXXXXXX X
    XXXXXXXX XXXXX X XXXXXXXXXXXXX X XX  X XXXXXXXXXXXXXXX
X
        X
        XXXX
            XXXXXX XXXXXX
            XXXXXXX XXXXXX
        X
    XX XXXXXX XXXXXX XXXXXX XX
    XXXXX X
        XXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXX
    X

    XX XXXXXX XXXXXXXXXX XX
    XXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXX XX X
        XXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXX
    X

    XX XXXXXX XXXXXXXXX XX
    XXXXX XX X
        XXXXXXXXXXXXXX XXX XXXXX XXXXX
    X

    XXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXX XXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXX
    X

    XXXXX XX X
        XXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXX
    X

    XX XXXX XXXXX XX
    XXXXX XXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
    X

    XX XXXXXX XXXXXXXXXXX XX
    XXX XX X
        XXXXXXX XXX XXXXX XXXXX
    X
XXXXXXXX

XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
XXXXXXXXXXXX XXXXXXXXX
XXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXX gettext(u'Amount') XXXXX
    XXXX gettext(u'Categoty') XXXXX
    XXXX gettext(u'Description') XXXXX
    XXXX gettext(u'Date') XXXXX
    XXXXXXXX
    XXXXXXX
    BBB BBBBBBB BB BBBBBBBB
        XXXX

        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXX
    BBBBBB
    XXXX
        XXXX gettext(u'Total') XXXXX
        XXXXXXXXX
    XXXXX
    XXXXXXXX
XXXXXXXX
XXXXXXX
XXXXXXX