BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
    BBBB BBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXX

        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XX
                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                        XXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX gettext(u'Expenses Summary') XXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Back') XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Summary') XXXX
            XXXXXX
            XXXXX
  XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXX XXXXXXXXXX
XXXXXX


        XXXXXX


        XXXXXX
    XXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
