BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBBBB

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXX
                        XXXX gettext(u'Set New Password') SSS SSS SSSSSSSSXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXX  XXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Already have an account?') SSSSSSS SSSS SS SSSSSSSS
                            XX XXXXXXBBB BBBBBBBXX gettext(u'Signin') SSSSSS XXXX XXXXXXXXXXX
                    XXXXXX
                XXXXXX

            XXXXXX
        XXXXXX


    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX


    XXXXXXX XXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX

BBBBBBBB BBBBBBB